version: '3.8'
services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.ollama:/usr/share/ollama/.ollama
    ports:
      - 11434:11434
    restart: always
